version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/src/client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels: ["dependencies"]

  - package-ecosystem: "gradle"
    directory: "/src/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

automerged_updates:
  - match:
      dependency_type: "all"
      update_type: "version-update:semver-patch"
    commit_message:
      prefix: "chore(deps):"
    merge_method: "squash"
